### PR TITLE
Allow the filtering for stable versions

### LINKED ISSUE #8: Allow filtering for stable versions
It would be also awesome if there would be an option to only use 'stable' versions, a.k.a. versions without pre-release identifiers.

For example cert-manager:

```log
[dry-run] Updating release cert-manager (cert-manager) from v0.11.0 to v0.12.0-beta.1
```

I'd like to only update to the latest stable versions, which in this case _is_ `v0.11.0`

### PR DESCRIPTION
**Pull request by cwrau**
Closes #8 

I don't know if the passing of the stable parameter to the HelmRelease is the best choice, but I didn't want to change too much.

### CODE REVIEW

**Comment by ekeih** [comment]
Hi @cwrau,
thank you for the contribution! :slightly_smiling_face: 
I think I would even go one step further and rename the flag to something like `--unstable` and default to false.
So the default behavior would be to ignore pre-releases and the user would have to enforce unstable updates.
What do you think?

**Comment by cwrau** [comment]
Sounds even better! 😄
I'll get right on it!

**Comment by pinkavaj** [comment]
What about another approach, getting curren helm chart version from HemlRelease, checking if it is stable or development and then choose proper upgrade method. This might work well because charts use SemVer 2.0.0.

This example is my expected useage pattern.

Example:
  * 1.2.3 -> upgrade to any stable version
  * 1.2.3-4.5.6 -> upgrade to any unstable version
  * 1.2.3-beta.2 -> upgrade to any unstable version starting with `1.2.3-beta`
  * 1.2.3-rc.4 -> upgrade to any unstable version starting with `1.2.3-rc`

**Review by ekeih — APPROVED** [review]

**Comment by ekeih** [comment]
@cwrau
Thanks for the new feature! :)
After publishing the release I realized that there was a space missing, so I added a minor adjustment: https://github.com/ekeih/heluxup/commit/f8f605161b810497559b1156c2a68c67f7980ddd
It is now released as 1.0.2
* https://github.com/ekeih/heluxup/releases
* https://pypi.org/project/heluxup/1.0.2/

@pinkavaj
I see you point, but I think the complexity of the change is bigger than this PR. So I went ahead and merged this change for now. Feel free to put your suggestion in a separate issue. (To be honest I will probably not implement it, but if you or someone else opens a PR I am happy to merge it.)

**Pull request merged**
